/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: fb855b150fd2ef5cfd3bb83dcc859279)
interface __BaseEnv_Env {
	SNAPSHOTS: KVNamespace;
	ASSETS: Fetcher;
	TURNSTILE_ENABLED: "false";
	LOSTARK_API_TOKEN: string;
	UPSTREAM_BUDGET: DurableObjectNamespace<import("./src/index").UpstreamBudget>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UpstreamBudget";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_ENABLED" | "LOSTARK_API_TOKEN">> {}
}
